### PR TITLE
Mention tracing in mlflow.org landing page

### PR DESCRIPTION
**Pull request by daniellok-db**
Carousel component:

Big screen:

https://github.com/user-attachments/assets/bbd7839a-bf0b-45f0-95fb-4016d4738e9d

Small screen:

https://github.com/user-attachments/assets/b60abb61-ba71-478a-b48b-72bd8a366e40

Cards:

(leads to tracing docs but doesn't work in dev environment)

https://github.com/user-attachments/assets/03cdcd42-6dad-44f8-b33b-ba4178e226e7

### CODE REVIEW

**Review by harupy — APPROVED** [review]
LGTM!

**Comment by harupy** [comment]
Is this a bug?

image

**Review by WeichenXu123 — APPROVED** [review]
LGTM! :)

**Comment by daniellok-db** [comment]
@harupy where do you see the render failure? i can't seem to get stackblitz to build

**Comment by harupy** [comment]
@daniellok-db I see the error on stackblitz.

**Pull request merged**
