### PR TITLE
Improve blog and release note landing page

### PR DESCRIPTION
**Pull request by harupy**
## Blog

image

## Release note

image

### CODE REVIEW

**Comment by daniellok-db** [comment]
The code lgtm, but seeing the preview, I feel like we should keep the release page as it was before.

The grid makes sense for the blog, because the images are nice to have, and people might be browsing old posts. 

However, for releases, people are probably just looking to see the latest updates. I think that the previous release page layout is more helpful because we can see a preview of what the release contains. With the grid change, the releases just look like a big wall of text. cc @BenWilson2 what do you think?

**Comment by harupy** [comment]
@daniellok-db thanks for the feedback! +1 for keeping the original release page.

**Comment by BenWilson2** [comment]
Agreed. And also, Haru, the blog layout looks amazing! Absolutely perfect!

**Comment by BenWilson2** [comment]
Checked at a few different resolutions. Some notes:

- At tablet rendering page sizes, the vertical justification of the cards starts to look a little odd (the blog authors names and photos start to be very misaligned vertically) 
- The text start of the blog title vertical alignment is contingent on the header image of the blog vertical scale. 

Can we set the 4 elements within the card (image, tags, title, and author) at distinct heights so that the alignment of all flexes and renders properly at different resolutions? It might make sense to do something like truncating the tags (only display 2?) and doing a max height with truncation of the title so that we don't have to have some crazy complex height wrangling logic within these <div> elements.

**Comment by harupy** [comment]
@BenWilson2 Distinct heights for each section sounds good. Truncating tags doesn't work if you have long tags. Can we remove them?

**Comment by daniellok-db** [comment]
took a look at the styling issues, i think the main problem is that the `<Blog>` component has way too many layers of nesting right now, so it's hard to apply a quick CSS fix:

https://github.com/mlflow/mlflow-website/blob/main/website/src/components/Blog/index.tsx#L10

at the moment we have four layers of divs:

```jsx
<div className={clsx("card", styles.card)}>
    <div className={clsx("card__body", styles.cardBody)}>
        <Link>
          <div className={styles.container}>
            {/* ... main content */}
```

we probably only need one. then we can group the elements like so:

```jsx
<div 
  className={/* combine card and cardBody, i believe it's possible to specify multiple classNames */}
  role="link">
  <div>
    {/* picture */}
    {/* tags */}
    {/* title */}
  </div>
  {/* author avatar */}
</div>
```

as for the tags spanning multiple lines... i don't think there's an easy pure-css solution for it. the best i can think of is:
1. Use `flex: nowrap; overflow: hidden; position: relative;` on the tag container div
2. In each tag, check if the element is by checking `element.offsetLeft + element.width` and check if it's greater than `element.offsetParent.width`
3. If so, set the tag to `display: none`

it's doable but yeah it's a bit troublesome.

**Comment by harupy** [comment]
Can we vertically stack the blog posts like this?

image

**Comment by harupy** [comment]
https://github.com/mlflow/mlflow-website/assets/17039389/2325df49-35ad-420e-99da-c8c68e3e4f20

**Review by daniellok-db — APPROVED** [review]
LGTM! I agree that vertical is simpler

**Pull request merged**
